use reqwest::Client;
use chrono::Utc;
use std::time::Duration;

use crate::models::{GitHubSearchResponse, RepositoryInfo, Issue};
use crate::db;

const GITHUB_API_BASE: &str = "https://api.github.com";

pub async fn fetch_and_store_issues() -> Result<(), Box<dyn std::error::Error>> {
    let client = Client::new();
    
    // Fetch issues with filters: label:good first issue, language:rust, state:open
    let query = "q=label:%22good%20first%20issue%22%20language:rust%20state:open&per_page=100";
    let url = format!("{}/search/issues?{}", GITHUB_API_BASE, query);
    
    tracing::info!("Fetching issues from: {}", url);
    
    let response = client.get(&url)
        .header("User-Agent", "gh-issue-browser")
        .timeout(Duration::from_secs(30))
        .send()
        .await?;
    
    let search_result: GitHubSearchResponse = response.json().await?;
    tracing::info!("Fetched {} issues", search_result.items.len());
    
    for github_issue in search_result.items {
        // Extract repo name from repository_url
        let repo_name = github_issue.repository_url
            .split('/')
            .rev()
            .take(2)
            .collect::<Vec<_>>()
            .into_iter()
            .rev()
            .collect::<Vec<_>>()
            .join("/");
        
        // Get or fetch stargazer count
        let star_count = get_or_fetch_stargazer_count(&client, &repo_name).await?;
        
        // Create issue record
        let issue = Issue {
            id: 0, // Will be auto-generated by DB
            repo_name,
            url: github_issue.url,
            creator: github_issue.user.login,
            created_at: github_issue.created_at,
            title: github_issue.title,
            labels: github_issue.labels.iter()
                .map(|l| l.name.clone())
                .collect::<Vec<_>>()
                .join(", "),
            star_count,
        };
        
        // Insert issue to database
        if let Err(e) = db::insert_issue(&issue) {
            tracing::warn!("Failed to insert issue {}: {:?}", issue.url, e);
        }
    }
    
    Ok(())
}

async fn get_or_fetch_stargazer_count(client: &Client, repo_name: &str) -> Result<i64, Box<dyn std::error::Error>> {
    // Check if we have cached stargazer count
    if let Ok(Some(cached)) = db::get_stargazer_count(repo_name) {
        let cached_time = chrono::DateTime::parse_from_rfc3339(&cached.updated_at)
            .map(|dt| dt.with_timezone(&Utc))
            .unwrap_or_else(|_| Utc::now());
        
        let age_hours = (Utc::now() - cached_time).num_hours();
        
        if age_hours < 24 {
            tracing::debug!("Using cached stargazer count for {}: {}", repo_name, cached.star_count);
            return Ok(cached.star_count);
        }
    }
    
    // Fetch from GitHub API
    let url = format!("{}/repos/{}", GITHUB_API_BASE, repo_name);
    tracing::debug!("Fetching stargazer count from: {}", url);
    
    let response = client.get(&url)
        .header("User-Agent", "gh-issue-browser")
        .timeout(Duration::from_secs(10))
        .send()
        .await?;
    
    let repo_info: RepositoryInfo = response.json().await?;
    
    // Store in database
    db::insert_or_update_stargazer_count(repo_name, repo_info.stargazers_count)?;
    
    Ok(repo_info.stargazers_count)
}
